kind: pipeline
name: default

steps:
- name: Submodule sync
  image: alpine/git
  commands:
    - "git submodule update --init"
- name: build
  image: plugins/hugo
  commands:
    - "hugo version"
    - "hugo --destination public --baseURL https://www.esamir.com"
- name: publish
  image: plugins/gh-pages
  settings:
    pages_directory: public
    upstream_name: https://github.com/safaci2000/safaci2000.github.io.git
    target_branch: master
    force_push: true
    delete: true
    username:
      from_secret: gh_username
    password:
      from_secret: gh_password
